AWSTemplateFormatVersion: 2010-09-09

Description: |
  Capstone Project CloudFormation Network Deployment.
  - VPC
  - Subnets
  - Internet Gateway
  - NAT Gateway
  - EIP

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names.
    Default: capstone
    Type: String

  VPCCIDR:
    Description: Enter the CIDR for the the VPC. Default is 10.0.0.0/16.
    Type: String
    Default: 10.0.0.0/16

  PUBSUBNET1CIDR:
    Description: Enter the CIDR for the Public Subnet 1. Default is 10.0.1.0/24.
    Type: String
    Default: 10.0.1.0/24

  PUBSUBNET2CIDR:
    Description: Enter the CIDR for the Public Subnet 2. Default is 10.0.2.0/24.
    Type: String
    Default: 10.0.2.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC

  IG:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-IG

  IGA:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IG
      VpcId: !Ref VPC

  PUBSUBNET1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [0, !GetAZs ""]
      CidrBlock: !Ref PUBSUBNET1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-PUBSUBNET1
      VpcId: !Ref VPC

  PUBSUBNET2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs ""]
      CidrBlock: !Ref PUBSUBNET2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-PUBSUBNET2
      VpcId: !Ref VPC

  PUBROUTETABLE:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub ${EnvironmentName}-PUBROUTETABLE
      VpcId: !Ref VPC

  PUBINTERNETROUTE:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IG
      RouteTableId: !Ref PUBROUTETABLE

  PUBROUTEASSOCIATION1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PUBROUTETABLE
      SubnetId: !Ref PUBSUBNET1

  PUBROUTEASSOCIATION2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PUBROUTETABLE
      SubnetId: !Ref PUBSUBNET2

Outputs:
  VPC:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${EnvironmentName}-VPC

  PUBSUBNET1:
    Description: The ID of the Public Subnet 1
    Value: !Ref PUBSUBNET1
    Export:
      Name: !Sub ${EnvironmentName}-PUBSUBNET1

  PUBSUBNET2:
    Description: The ID of the Public Subnet 2
    Value: !Ref PUBSUBNET2
    Export:
      Name: !Sub ${EnvironmentName}-PUBSUBNET2

  PUBSUBNETS:
    Description: A list of the Private Subnets
    Value: !Join [",", [!Ref PUBSUBNET1, !Ref PUBSUBNET2]]
    Export:
      Name: !Sub ${EnvironmentName}-PUBSUBNETS
