version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.2.0
jobs:
  test-lint:
    docker:
      - image: circleci/python:3.6.7-stretch
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
            curl -sL -o hadolint "https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m)"
            sudo install hadolint /usr/local/bin/
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lints!
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            make lint

  upload-docker:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build --tag=uda-final .
            docker image ls
      - run:
          name: Upload image to dockerhub
          command: |
            DOCKER_PATH=dienpp/uda-final
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker tag uda-final $DOCKER_PATH
            docker push $DOCKER_PATH

  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yum install -y tar gzip
      - run:
          name: Ensure EKS network exists
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/network.yml \
              --tags project=uda-capstone \
              --stack-name "capstone-eks-network" \
              --region ${AWS_DEFAULT_REGION}
      - run:
          name: Ensure EKS Cluster exists
          no_output_timeout: 20m
          command: |
            aws cloudformation deploy \
              --template-file .circleci/files/eks.yml \
              --tags project=uda-capstone \
              --stack-name "capstone-eks-cluster-node" \
              --region ${AWS_DEFAULT_REGION} \
              --capabilities CAPABILITY_NAMED_IAM

  deploy:
    docker:
      - image: cimg/python:3.11.4
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
        # sửa tên cluster
        default: "EKSCLUSTER"
      aws-region:
        description: |
          AWS region
        type: string
        default: "us-east-1"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            sudo apt install -y tar gzip curl
      - kubernetes/install-kubectl
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: .circleci/kubernetes/deployment.yml
          resource-name: deployment/uda-final
          get-rollout-status: true
          show-kubectl-command: true
      - kubernetes/create-or-update-resource:
          resource-file-path: .circleci/kubernetes/loadbalancer.yml
          resource-name: service/uda-final
      - kubernetes/create-or-update-resource:
          resource-file-path: .circleci/kubernetes/aws-authen-cm.yml
          resource-name: configmap/aws-auth
      - run:
          name: Test cluster
          command: |
            kubectl get nodes
            kubectl get deployment
            kubectl get pod -o wide
            kubectl get services
      - run:
          name: Cleaning up
          command: docker system prune

workflows:
  default:
    jobs:
      - test-lint
      - upload-docker:
          requires:
            - test-lint
          filters:
            branches:
              only:
                - master
      - deploy-infrastructure:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - deploy-infrastructure
            - upload-docker
